version: '3.8'
services:
  mongodb:
    image: mongo:4.2.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    command: ["--auth"]